const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = {
  required: [
    "matchScore",
    "technicalQuestions",
    "behavioralQuestions",
    "skillGaps",
    "preparationPlan",
    "title",
  ],
  additionalProperties: false,
  type: "object",
  properties: {
    matchScore: { type: "number" },
    technicalQuestions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          intention: { type: "string" },
          answer: { type: "string" },
        },
        required: ["question", "intention", "answer"],
      },
    },
    behavioralQuestions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          intention: { type: "string" },
          answer: { type: "string" },
        },
        required: ["question", "intention", "answer"],
      },
    },
    skillGaps: {
      type: "array",
      items: {
        type: "object",
        properties: {
          skill: {
            type: "string",
          },
          severity: {
            type: "string",
            enum: ["low", "medium", "high"],
          },
        },
        required: ["skill", "severity"],
      },
    },

    preparationPlan: {
      type: "array",
      items: {
        type: "object",
        properties: {
          day: {
            type: "number",
          },
          focus: {
            type: "string",
          },
          tasks: {
            type: "array",
            items: {
              type: "string",
            },
          },
        },
        required: ["day", "focus", "tasks"],
      },
    },
    title: {
      type: "string",
      description: "Maximum 100 characters",
    },
  },
};

async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `Generate an interview report.
  IMPORTANT:

- For every question:
  - question = actual interview question
  - intention = why interviewer asks it
  - answer = detailed answer strategy including:
      * approach
      * key points to mention
      * common mistakes to avoid
      * sample answer outline

- Generate at least 5 technical questions.
- Generate at least 3 behavioral questions.
- Generate a realistic preparation plan.
- Generate a title of the job for which the interview report was generated

For every question:

- intention: maximum 30 words
- answer: maximum 120 words
Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}`;

  const response = await ai.models.generateContent({
    model: "gemini-3.1-flash-lite",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseJsonSchema: interviewReportSchema,
    },
  });
  const responseText = response.text;
  try {
    return JSON.parse(responseText);
  } catch (err) {
    console.error("JSON Parse Error:", err.message);
    throw err;
  }
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle2" });

  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" },
  });

  await browser.close();
  return pdfBuffer;
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const resumeSchema = {
    type: "object",
    properties: {
      html: {
        type: "string",
      },
    },
    required: ["html"],
  };
  const prompt = `Generate resume for a candidate with the following details:
  Resume:${resume}
  Self Description: ${selfDescription}
  Job Description:${jobDescription}
  the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer
  the resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML should be well-formatted and structured, making it easy to read and visible
  the content of the resume should not sound like it is generated by Ai and should be as close as possible to a real human-written resume
  you can highlight the content using some colors or different font styles but the overall design should be simple and professional
  `;
  let response;
  try {
    response = await ai.models.generateContent({
      model: "gemini-3.1-flash-lite",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: resumeSchema,
      },
    });
  } catch (error) {
    console.error("FULL ERROR:", error);
    console.error("CAUSE:", error.cause);
    throw error;
  }

  const jsonContent = JSON.parse(response.text);
  const pdfBuffer = await generatePdfFromHtml(jsonContent.html);
  return pdfBuffer;
}
module.exports = { generateInterviewReport, generateResumePdf };
